sudo: required
services:
  - docker

before_install:
  - docker build -t evilfiend/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true evilfiend/react-test npm run test -- --coverage

after_success:
  - docker build -t evilfiend/multi-client ./client
  - docker build -t evilfiend/multi-nginx ./nginx
  - docker build -t evilfiend/multi-server ./server
  - docker build -t evilfiend/multi-worker ./worker
    # Pushing to docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin #To login into Docker
  - docker push evilfiend/multi-client
  - docker push evilfiend/multi-server
  - docker push evilfiend/multi-nginx
  - docker push evilfiend/multi-worker